export const SUCCESS_MESSAGES = {
    ALBUMS: 'Albums fetched successfully',
    ALBUM_MEDIA: 'Album media fetched successfully',
    MEDIA: 'Media fetched successfully',
    SEARCH_RESULTS: 'Search results fetched successfully',
    ALL_PROFILES: 'Profiles fetched successfully',
    PROFILE: 'Profile fetched successfully',
    PHOTO_DETAILS: 'Photo details fetched successfully',
    SIMILAR_PHOTOS: 'Similar photos fetched successfully',
    CAPTION_UPDATED: 'Caption updated successfully',
    SCENES: 'Scenes fetched successfully',
    SCENE_PHOTOS: 'Scene photos fetched successfully',
    FOLDER_MOUNT_START: 'Folder mounted. Processing images... This may take a while.',
    FOLDER_MOUNT_FINISH: 'Go to Albums to view the images',
}

export const ERROR_MESSAGES = {
    ALBUMS: 'Error while fetching albums',
    ALBUM_MEDIA: 'Error while fetching album media',
    MEDIA: 'Error while fetching media',
    SEARCH_RESULTS: 'Error while fetching the search results',
    ALL_PROFILES: 'Error while fetching profiles',
    PROFILE: 'Error while fetching profile',
    PHOTO_DETAILS: 'Error while fetching photo details',
    SIMILAR_PHOTOS: 'Error while fetching similar photos',
    CAPTION_UPDATED: 'Error while updating caption',
    SCENES: 'Error while fetching scenes',
    SCENE_PHOTOS: 'Error while fetching scene photos',
    UPLOAD_IMAGE_FOR_SEARCH: 'Please upload an image to search',
    ENTER_TEXT_TO_SEARCH: 'Please enter text to search',
    FOLDER_MOUNT_START: 'Error while mounting folder',
    SELECT_FOLDER: 'Please select a folder',
    FOLDER_MOUNT_FINISH: 'Error while adding the new album',
}